
-- Add cohort column to students table
ALTER TABLE public.students 
ADD COLUMN cohort TEXT NOT NULL DEFAULT 'March 2025 Pilot';

-- Create index on cohort for performance
CREATE INDEX idx_students_cohort ON public.students(cohort);

-- Create cohorts reference table
CREATE TABLE public.cohorts (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  start_date DATE,
  end_date DATE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Insert the two cohorts
INSERT INTO public.cohorts (name, start_date, is_active) VALUES
('March 2025 Pilot', '2025-03-15', true),
('June 2025', '2025-06-01', true);

-- Insert all 83 June 2025 students
INSERT INTO public.students (first_name, last_name, email, cohort, created_at, updated_at) VALUES
('Aeolus', 'Camacho', 'aeolus.camacho@pursuit.org', 'June 2025', now(), now()),
('Agyeman', 'Osei Kuffour', 'agyeman.ok@pursuit.org', 'June 2025', now(), now()),
('Aimish', 'Jahangir', 'aimish.jahangir@pursuit.org', 'June 2025', now(), now()),
('Lovosa (Aina)', 'Rasolofoniaina', 'aina.rasolofoniaina@pursuit.org', 'June 2025', now(), now()),
('Arielle', 'Pine', 'arielle.pine@pursuit.org', 'June 2025', now(), now()),
('Brandon', 'Bain', 'brandon.bain@pursuit.org', 'June 2025', now(), now()),
('Christian', 'Almonte', 'christian.almonte@pursuit.org', 'June 2025', now(), now()),
('Christian', 'Martinez', 'christian.martinez@pursuit.org', 'June 2025', now(), now()),
('Coreen', 'Rogers', 'coreen.rogers@pursuit.org', 'June 2025', now(), now()),
('Mohamed (Lamine)', 'Coulibaly', 'lamine.coulibaly@pursuit.org', 'June 2025', now(), now()),
('Dan', 'Lee', 'dan.lee@pursuit.org', 'June 2025', now(), now()),
('Darren', 'Williams', 'darren.williams@pursuit.org', 'June 2025', now(), now()),
('Darryl', 'Carpen', 'darryl.carpen@pursuit.org', 'June 2025', now(), now()),
('David', 'Omokagbor', 'david.omokagbor@pursuit.org', 'June 2025', now(), now()),
('David', 'White Wolf', 'david.ww@pursuit.org', 'June 2025', now(), now()),
('David', 'Wyche', 'david.wyche@pursuit.org', 'June 2025', now(), now()),
('Dawan', 'Sawyer', 'dawan.sawyer@pursuit.org', 'June 2025', now(), now()),
('Diane', 'Ludin', 'diane.ludin@pursuit.org', 'June 2025', now(), now()),
('Duanech', 'Acosta', 'duanech.acosta@pursuit.org', 'June 2025', now(), now()),
('Dunstan', 'Wallace', 'dunstan.wallace@pursuit.org', 'June 2025', now(), now()),
('Duvall', 'Morgan', 'duvall.morgan@pursuit.org', 'June 2025', now(), now()),
('Dwight', 'Williams', 'dwight.williams@pursuit.org', 'June 2025', now(), now()),
('Edgar', 'Cardona', 'edgar.cardona@pursuit.org', 'June 2025', now(), now()),
('El''aan', 'MonteFiore', 'elaan.montefiore@pursuit.org', 'June 2025', now(), now()),
('Elliot', 'Chen', 'elliot.chen@pursuit.org', 'June 2025', now(), now()),
('Elvis', 'Onya', 'elvis.onya@pursuit.org', 'June 2025', now(), now()),
('eric', 'estevez', 'eric.estevez@pursuit.org', 'June 2025', now(), now()),
('Frank', 'Felipe', 'frank.felipe@pursuit.org', 'June 2025', now(), now()),
('Gary', 'Gonzalez', 'gary.gonzalez@pursuit.org', 'June 2025', now(), now()),
('George', 'Peck', 'george.peck@pursuit.org', 'June 2025', now(), now()),
('Habtamu', 'Berhe', 'habtamu.berhe@pursuit.org', 'June 2025', now(), now()),
('Hamed', 'Diaby', 'hamed.diaby@pursuit.org', 'June 2025', now(), now()),
('Harry', 'StCloud', 'harry.stcloud@pursuit.org', 'June 2025', now(), now()),
('Ian', 'Patino', 'ian.patino@pursuit.org', 'June 2025', now(), now()),
('idris', 'bello', 'idris.bello@pursuit.org', 'June 2025', now(), now()),
('James', 'Nelson', 'james.nelson@pursuit.org', 'June 2025', now(), now()),
('James', 'Turzio', 'james.turzio@pursuit.org', 'June 2025', now(), now()),
('Jason', 'Broomes', 'jason.broomes@pursuit.org', 'June 2025', now(), now()),
('Justin', 'Meacock', 'justin.meacock@pursuit.org', 'June 2025', now(), now()),
('Kadija', 'Camara', 'kadija.camara@pursuit.org', 'June 2025', now(), now()),
('Kaung', 'Kyaw', 'kaung.kyaw@pursuit.org', 'June 2025', now(), now()),
('Kristian', 'Adamson', 'kristian.adamson@pursuit.org', 'June 2025', now(), now()),
('Leo', 'Victorio Juarez', 'leo.vj@pursuit.org', 'June 2025', now(), now()),
('Luis', 'Cruz', 'luis.cruz@pursuit.org', 'June 2025', now(), now()),
('Luis', 'Puga', 'luis.puga@pursuit.org', 'June 2025', now(), now()),
('Mansor', 'Diallo', 'mansor.diallo@pursuit.org', 'June 2025', now(), now()),
('Maysa', 'Khedr', 'maysa.khedr@pursuit.org', 'June 2025', now(), now()),
('Michael', 'Chabler', 'michael.chabler@pursuit.org', 'June 2025', now(), now()),
('Miguel', 'Custodio', 'miguel.custodio@pursuit.org', 'June 2025', now(), now()),
('Mikhail', 'James', 'mikhail.james@pursuit.org', 'June 2025', now(), now()),
('Moe', 'Oo', 'moe.oo@pursuit.org', 'June 2025', now(), now()),
('Mouhazba', 'ba', 'mouhazba.ba@pursuit.org', 'June 2025', now(), now()),
('Muhammad', 'Ali', 'muhammad.ali@pursuit.org', 'June 2025', now(), now()),
('Musa', 'Abdelsayed', 'musa.abdelsayed@pursuit.org', 'June 2025', now(), now()),
('Nadira', 'Salam', 'nadira.salam@pursuit.org', 'June 2025', now(), now()),
('Najee', 'Jeremiah', 'najee.jeremiah@pursuit.org', 'June 2025', now(), now()),
('Naomi', 'Wilson', 'naomi.wilson@pursuit.org', 'June 2025', now(), now()),
('Oscar', 'Comunidad', 'oscar.comunidad@pursuit.org', 'June 2025', now(), now()),
('Patrick', 'Michel', 'patrick.michel@pursuit.org', 'June 2025', now(), now()),
('Pedro', 'Martins', 'pedro.martins@pursuit.org', 'June 2025', now(), now()),
('Qiquan', 'Wei', 'qiquan.wei@pursuit.org', 'June 2025', now(), now()),
('Rachel', 'Stroy', 'rachel.stroy@pursuit.org', 'June 2025', now(), now()),
('Ramesh', 'Beharry', 'ramesh.beharry@pursuit.org', 'June 2025', now(), now()),
('Rammer', 'Martínez Sánchez', 'rammer.ms@pursuit.org', 'June 2025', now(), now()),
('Ramon', 'Rodriguez', 'ramon.rodriguez@pursuit.org', 'June 2025', now(), now()),
('roderick', 'baldwin', 'roderick.baldwin@pursuit.org', 'June 2025', now(), now()),
('Ronin', 'Ruiz', 'ronin.ruiz@pursuit.org', 'June 2025', now(), now()),
('Rosie', 'Ramirez', 'rosie.ramirez@pursuit.org', 'June 2025', now(), now()),
('Rukayatu', 'Gariba', 'rukayatu.gariba@pursuit.org', 'June 2025', now(), now()),
('Ryan', 'Anderson', 'ryan.anderson@pursuit.org', 'June 2025', now(), now()),
('Ryan', 'Holgate', 'ryan.holgate@pursuit.org', 'June 2025', now(), now()),
('Sharmin', 'Sultana', 'sharmin.sultana@pursuit.org', 'June 2025', now(), now()),
('Siddharth', 'Nimbvikar', 'siddharth.nimbvikar@pursuit.org', 'June 2025', now(), now()),
('Sumaya', 'Abdelwakeel', 'sumaya.abdelwakeel@pursuit.org', 'June 2025', now(), now()),
('Tracy', 'Byrdsong', 'tracy.byrdsong@pursuit.org', 'June 2025', now(), now()),
('Whitney', 'Orphee', 'whitney.orphee@pursuit.org', 'June 2025', now(), now()),
('William', 'Ortega', 'william.ortega@pursuit.org', 'June 2025', now(), now()),
('Yuko', 'Ichihara', 'yuko.ichihara@pursuit.org', 'June 2025', now(), now()),
('Yuriy', 'Aronov', 'yuriy.aronov@pursuit.org', 'June 2025', now(), now()),
('Zoha', 'Khalid', 'zoha.khalid@pursuit.org', 'June 2025', now(), now()),
('Ebony', 'Bolt', 'ebony.bolt@pursuit.org', 'June 2025', now(), now()),
('Penelope', 'Trent', 'penelope.trent@pursuit.org', 'June 2025', now(), now()),
('Angelo', 'Blas', 'angelo.blas@pursuit.org', 'June 2025', now(), now());
