// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emswwbojtxipisaqfmrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtc3d3Ym9qdHhpcGlzYXFmbXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTYwMzYsImV4cCI6MjA1ODIzMjAzNn0.4CtRdVEGlvpIalrGRy-nJ3C3Z9X-YIKtqK-s_AmgmGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);